0-transfer_file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -14,3 +14,29 @@ PATH_TO_SSH_KEY=$4
 
 # Transfer the file using scp with strict host key checking disabled
 scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP:~/"
+
+
+
+if [ $# -lt 4 ]; then
+    echo "Usage: ${0#./} PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
+fi
+
+# Assign parameters to variables
+PATH_TO_FILE=$1
+IP=$2
+USERNAME=$3
+ATH_TO_SSH_KEY=$4
+
+# Check if the local file exists
+if [ ! -f "$PATH_TO_FILE" ]; then
+    echo "Error: File '$PATH_TO_FILE' does not exist."
+    exit 1
+fi
+
+# Transfer the file using SCP
+if [ $# -eq 4 ]; then
+    scp -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP":~/
+else
+    scp -o StrictHostKeyChecking=no -i "$ATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP":~/
+fi
